---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "serviceAccountName" .}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "roleName" .}}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "roleBindingName" .}}
roleRef:
  kind: Role
  name: {{ template "roleName" .}}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dockerregistrykeyName" .}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

---
{{ if .Values.dockerImage }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{template "deploymentName" .}}
  labels:
    app: {{ template "labelName" .}}
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "labelName" .}}
  template:
    metadata:
      labels:
        app: {{ template "labelName" .}}
    spec:
      serviceAccountName: {{ template "serviceAccountName" .}}
      containers:
        - name: gowebapp
          image: {{ .Values.dockerImage }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 100
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 100
      imagePullSecrets:
        - name: {{ template "dockerregistrykeyName" .}}
{{ end }}

---  
{{ if .Values.dockerImage }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "serviceName" .}}
  labels:
    name: {{ template "labelName" .}}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector: 
    app: {{ template "labelName" .}}
{{ end }}

---
{{ if .Values.dockerImage }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ingressName" .}}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls: # < placing a host in the TLS config will indicate a certificate should be created
    - hosts:
        - {{ template "webappDomainName" .}}
      secretName: webapp-acme-crt-secret
  rules:
  - host: {{ template "webappDomainName" .}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "serviceName" .}}
          servicePort: 8000
{{ end }}
